"""Add bio and social_links to users

Revision ID: 04c2b778d192
Revises: 11d2f957fac7
Create Date: 2026-03-15 00:41:34.443614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c2b778d192'
down_revision: Union[str, Sequence[str], None] = '11d2f957fac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('social_links', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'social_links')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
