"""add_transports_to_checklists

Revision ID: 11d2f957fac7
Revises: c16b574f06f9
Create Date: 2026-03-14 17:29:59.129942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11d2f957fac7'
down_revision: Union[str, Sequence[str], None] = 'c16b574f06f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklists', sa.Column('transports', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklists', 'transports')
    # ### end Alembic commands ###
