"""add_address_to_itinerary_events

Revision ID: 11d6bf61d0c8
Revises: fcc9014dce91
Create Date: 2026-03-12 23:03:17.714016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d6bf61d0c8'
down_revision: Union[str, Sequence[str], None] = 'fcc9014dce91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary_events', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itinerary_events', 'address')
    # ### end Alembic commands ###
