"""add_follow_requests

Revision ID: 166f2de7b1ba
Revises: 04c2b778d192
Create Date: 2026-03-15 01:25:57.396746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166f2de7b1ba'
down_revision: Union[str, Sequence[str], None] = '04c2b778d192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_requests_from_user_id'), 'follow_requests', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_follow_requests_id'), 'follow_requests', ['id'], unique=False)
    op.create_index(op.f('ix_follow_requests_to_user_id'), 'follow_requests', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_requests_to_user_id'), table_name='follow_requests')
    op.drop_index(op.f('ix_follow_requests_id'), table_name='follow_requests')
    op.drop_index(op.f('ix_follow_requests_from_user_id'), table_name='follow_requests')
    op.drop_table('follow_requests')
    # ### end Alembic commands ###
