"""add checklist state fields

Revision ID: 517964269cb0
Revises: bc97ed269f9c
Create Date: 2025-07-23 16:24:54.314340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '517964269cb0'
down_revision: Union[str, Sequence[str], None] = 'bc97ed269f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklists', sa.Column('checked_items', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('checklists', sa.Column('removed_items', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('checklists', sa.Column('added_items', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklists', 'added_items')
    op.drop_column('checklists', 'removed_items')
    op.drop_column('checklists', 'checked_items')
    # ### end Alembic commands ###
