"""add tg_user_id to checklists

Revision ID: bc97ed269f9c
Revises: f0d494aaa370
Create Date: 2025-07-23 15:24:41.281368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc97ed269f9c'
down_revision: Union[str, Sequence[str], None] = 'f0d494aaa370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем, существует ли колонка tg_user_id перед добавлением
    # (она уже может быть создана в миграции f0d494aaa370)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('checklists')]
    
    if 'tg_user_id' not in columns:
        op.add_column('checklists', sa.Column('tg_user_id', sa.String(), nullable=True))
    
    # Проверяем, существует ли индекс перед созданием
    indexes = [idx['name'] for idx in inspector.get_indexes('checklists')]
    if 'ix_checklists_tg_user_id' not in indexes:
        op.create_index(op.f('ix_checklists_tg_user_id'), 'checklists', ['tg_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklists_tg_user_id'), table_name='checklists')
    op.drop_column('checklists', 'tg_user_id')
    # ### end Alembic commands ###
