"""add_extra_data_to_notifications

Revision ID: c16b574f06f9
Revises: 295ba72b3917
Create Date: 2026-03-14 03:33:48.242846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16b574f06f9'
down_revision: Union[str, Sequence[str], None] = '295ba72b3917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('extra_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'extra_data')
    # ### end Alembic commands ###
