"""add_hidden_sections

Revision ID: dce47f10210d
Revises: fb3f3185a659
Create Date: 2026-03-13 23:58:05.985441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dce47f10210d'
down_revision: Union[str, Sequence[str], None] = 'fb3f3185a659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklists', sa.Column('hidden_sections', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklists', 'hidden_sections')
    # ### end Alembic commands ###
