"""Add followers association table

Revision ID: f805f6cb54b1
Revises: b5e8f2a1c3d7
Create Date: 2026-03-12 21:25:22.760074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f805f6cb54b1'
down_revision: Union[str, Sequence[str], None] = 'b5e8f2a1c3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.drop_constraint(op.f('city_attractions_city_name_key'), 'city_attractions', type_='unique')
    op.drop_index(op.f('ix_city_attractions_city_name'), table_name='city_attractions')
    op.create_index(op.f('ix_city_attractions_city_name'), 'city_attractions', ['city_name'], unique=True)
    op.alter_column('users', 'avatar',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_city_attractions_city_name'), table_name='city_attractions')
    op.create_index(op.f('ix_city_attractions_city_name'), 'city_attractions', ['city_name'], unique=False)
    op.create_unique_constraint(op.f('city_attractions_city_name_key'), 'city_attractions', ['city_name'], postgresql_nulls_not_distinct=False)
    op.drop_table('followers')
    # ### end Alembic commands ###
