"""Add followers association table

Revision ID: f805f6cb54b1
Revises: b5e8f2a1c3d7
Create Date: 2026-03-12 21:25:22.760074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'f805f6cb54b1'
down_revision: Union[str, Sequence[str], None] = 'b5e8f2a1c3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'city_attractions' in existing_tables:
        unique_constraints = {
            constraint["name"]
            for constraint in inspector.get_unique_constraints('city_attractions')
            if constraint.get("name")
        }
        indexes = {
            index["name"]
            for index in inspector.get_indexes('city_attractions')
            if index.get("name")
        }

        constraint_name = op.f('city_attractions_city_name_key')
        index_name = op.f('ix_city_attractions_city_name')

        if constraint_name in unique_constraints:
            op.drop_constraint(constraint_name, 'city_attractions', type_='unique')
        if index_name in indexes:
            op.drop_index(index_name, table_name='city_attractions')

        op.create_index(index_name, 'city_attractions', ['city_name'], unique=True)
    user_columns = {column["name"] for column in inspector.get_columns('users')}
    if 'avatar' not in user_columns:
        op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    else:
        op.alter_column('users', 'avatar',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_columns = {column["name"] for column in inspector.get_columns('users')}
    if 'avatar' in user_columns:
        op.alter_column('users', 'avatar',
                   existing_type=sa.String(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'city_attractions' in existing_tables:
        indexes = {
            index["name"]
            for index in inspector.get_indexes('city_attractions')
            if index.get("name")
        }
        index_name = op.f('ix_city_attractions_city_name')
        constraint_name = op.f('city_attractions_city_name_key')

        if index_name in indexes:
            op.drop_index(index_name, table_name='city_attractions')
        op.create_index(index_name, 'city_attractions', ['city_name'], unique=False)
        op.create_unique_constraint(constraint_name, 'city_attractions', ['city_name'], postgresql_nulls_not_distinct=False)
    op.drop_table('followers')
    # ### end Alembic commands ###
