"""add_user_backpacks

Revision ID: fb3f3185a659
Revises: 11d6bf61d0c8
Create Date: 2026-03-13 23:16:11.613227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb3f3185a659'
down_revision: Union[str, Sequence[str], None] = '11d6bf61d0c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_backpacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('items', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('checked_items', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('added_items', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('removed_items', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_backpacks_checklist_id'), 'user_backpacks', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_user_backpacks_id'), 'user_backpacks', ['id'], unique=False)
    op.create_index(op.f('ix_user_backpacks_user_id'), 'user_backpacks', ['user_id'], unique=False)
    op.add_column('checklists', sa.Column('invite_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_checklists_invite_token'), 'checklists', ['invite_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklists_invite_token'), table_name='checklists')
    op.drop_column('checklists', 'invite_token')
    op.drop_index(op.f('ix_user_backpacks_user_id'), table_name='user_backpacks')
    op.drop_index(op.f('ix_user_backpacks_id'), table_name='user_backpacks')
    op.drop_index(op.f('ix_user_backpacks_checklist_id'), table_name='user_backpacks')
    op.drop_table('user_backpacks')
    # ### end Alembic commands ###
