"""add_itinerary_events

Revision ID: fcc9014dce91
Revises: f805f6cb54b1
Create Date: 2026-03-12 21:48:50.468566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc9014dce91'
down_revision: Union[str, Sequence[str], None] = 'f805f6cb54b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_events_checklist_id'), 'itinerary_events', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_itinerary_events_id'), 'itinerary_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_events_id'), table_name='itinerary_events')
    op.drop_index(op.f('ix_itinerary_events_checklist_id'), table_name='itinerary_events')
    op.drop_table('itinerary_events')
    # ### end Alembic commands ###
